let products = [
  {
    id: 1,
    prodName: "Lovely Dress For Girls",
    price: "LE 780.00",
    imgPath: "../images/Products/girl7.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 2,
    prodName: "Baby set",
    price: "LE 800.00",
    imgPath: "../images/Products/baby2.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "baby",
    fav: false,
    inCart: false,
    sizes: [3, 5, 7],
  },
  {
    id: 3,
    prodName: "Lovely Dress For Girls",
    price: "LE 599.00",
    imgPath: "../images/Products/girl6.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 4,
    prodName: "Baby set",
    price: "LE 450.00",
    imgPath: "../images/Products/baby5.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "baby",
    fav: false,
    inCart: false,
    sizes: [3, 8],
  },
  {
    id: 5,
    prodName: "Boy Suit",
    price: "LE 500.00",
    imgPath: "../images/Products/boy6.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [18, 20],
  },
  {
    id: 6,
    prodName: "Lovely Dress For Girls",
    price: "LE 990.00",
    imgPath: "../images/Products/girl8.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 7,
    prodName: "Baby set",
    price: "LE 900.00",
    imgPath: "../images/Products/baby7.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "baby",
    fav: false,
    inCart: false,
    sizes: [6, 8, 10, 12],
  },
  {
    id: 8,
    prodName: "Children's Desert Sky Tee",
    price: "LE 250.00",
    imgPath: "../images/Products/boy0.webp",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [14, 16, 18],
  },
  {
    id: 9,
    prodName: "baby blue suite",
    price: "LE 600.00",
    imgPath: "../images/Products/boy1.jpg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [16, 18, 20, 22],
  },
  {
    id: 10,
    prodName: "Baby set",
    price: "LE 800.00",
    imgPath: "../images/Products/boy2.jpg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [14, 16],
  },
  {
    id: 11,
    prodName: "Baby set",
    price: "LE 380.00",
    imgPath: "../images/Products/boy3.jpg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [12, 14],
  },
  {
    id: 12,
    prodName: "boy suit",
    price: "LE 800.00",
    imgPath: "../images/Products/boy4.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [16, 18, 20],
  },
  {
    id: 13,
    prodName: "Baby set",
    price: "LE 1300.00",
    imgPath: "../images/Products/baby6.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "baby",
    fav: false,
    inCart: false,
    sizes: [5, 7, 9, 12],
  },
  {
    id: 14,
    prodName: "boy clothes",
    price: "LE 750.00",
    imgPath: "../images/Products/boy5.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [14],
  },
  {
    id: 15,
    prodName: "Baby set",
    price: "LE 300.00",
    imgPath: "../images/Products/baby3.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "baby",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 16,
    prodName: "Dress ",
    price: "LE 900.00",
    imgPath: "../images/Products/girl1.png",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [13, 15],
  },
  {
    id: 17,
    prodName: "Baby set",
    price: "LE 500.00",
    imgPath: "../images/Products/baby1.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "baby",
    fav: false,
    inCart: false,
    sizes: [4, 6, 8],
  },
  {
    id: 18,
    prodName: "Boy Suit",
    price: "LE 1200.00",
    imgPath: "../images/Products/boy8.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [14, 16, 18, 20, 22],
  },
  {
    id: 19,
    prodName: "Boy Suit",
    price: "LE 1500.00",
    imgPath: "../images/Products/boy9.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [18, 22],
  },
  {
    id: 20,
    prodName: "Lovely Dress For Girls",
    price: "LE 1600.00",
    imgPath: "../images/Products/girl2.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [17, 19, 25],
  },
  {
    id: 21,
    prodName: "Lovely Dress For Girls",
    price: "LE 800.00",
    imgPath: "../images/Products/girl3.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "gril",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 22,
    prodName: "Lovely Dress For Girls",
    price: "LE 500.00",
    imgPath: "../images/Products/girl4.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 23,
    prodName: "Lovely Dress For Girls",
    price: "LE 650.00",
    imgPath: "../images/Products/girl5.jpg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 24,
    prodName: "Boy Suit",
    price: "LE 660.00",
    imgPath: "../images/Products/boy7.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "boy",
    fav: false,
    inCart: false,
    sizes: [16],
  },
  {
    id: 25,
    prodName: "Baby set",
    price: "LE 700.00",
    imgPath: "../images/Products/baby4.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "baby",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 26,
    prodName: "Lovely Dress For Girls",
    price: "LE 450.00",
    imgPath: "../images/Products/girl9.jpg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
  {
    id: 27,
    prodName: "Lovely Dress For Girls",
    price: "LE 1300.00",
    imgPath: "../images/Products/girl10.jpeg",
    discription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nesciunt?",
    type: "girl",
    fav: false,
    inCart: false,
    sizes: [3, 6, 8],
  },
];

export default products;
